"""Run SQL/03_data_quality.sql and SQL/05_business_questions.sql; write SQL/query_results.md."""
import re
import time
from pathlib import Path

import pandas as pd
import psycopg

from importlib import import_module

ROOT = Path(__file__).resolve().parents[1]
CONNINFO = import_module("02_load_postgres").CONNINFO
FILES = ["03_data_quality.sql", "05_business_questions.sql"]


def split_queries(sql_text):
    """Yield (title, sql) for each block that starts with a '-- Qn: title' comment."""
    blocks = re.split(r"^-- (Q\d+: .+)$", sql_text, flags=re.M)
    for title, body in zip(blocks[1::2], blocks[2::2]):
        # drop continuation comment lines directly under the title
        body = re.sub(r"^\A(--.*\n)+", "", body.lstrip("\n"))
        yield title.strip(), body.strip()


def main():
    out = ["# SQL Query Results", "",
           "Generated by `Python/03_run_sql_queries.py` against the `hospital_finance` PostgreSQL database.", ""]
    with psycopg.connect(CONNINFO) as conn:
        for name in FILES:
            out += [f"## {name}", ""]
            for title, sql in split_queries((ROOT / "SQL" / name).read_text(encoding="utf-8-sig")):
                t = time.time()
                with conn.cursor() as cur:
                    cur.execute(sql)
                    df = pd.DataFrame(cur.fetchall(), columns=[c.name for c in cur.description])
                out += [f"### {title}", "", "```sql", sql, "```", "",
                        df.to_markdown(index=False, floatfmt=",.2f") if len(df) else "_no rows_", ""]
                print(f"{name[:2]} {title[:80]:<80} {len(df):>4} rows {time.time() - t:5.1f}s")
    (ROOT / "SQL" / "query_results.md").write_text("\n".join(out), encoding="utf-8")
    print("wrote SQL/query_results.md")


if __name__ == "__main__":
    main()
